{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.gatekeeper "name" "gatekeeper" "defaults" (include "bigbang.defaults.gatekeeper" .)) }}
{{- end }}

{{- define "bigbang.defaults.gatekeeper" -}}
image:
  pullSecrets:
  - name: private-registry
postInstall:
  labelNamespace:
    enabled: false
    image:
      pullSecrets:
      - name: private-registry
postUpgrade:
  cleanupCRD:
    image:
      pullSecrets:
      - name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
violations:  # Try to keep this in alpha order to make it easier to find keys

  allowedDockerRegistries:
    parameters:
      repos:
        - registry1.dso.mil
        - registry.dso.mil
      {{- if .Values.addons.mattermost.enabled }}
      excludedResources:
        # Mattermost needs postgres:13 image and cannot override the upstream
        - mattermost/init-check-database
      {{- end }}

  {{- if or .Values.monitoring.enabled .Values.fluentbit.enabled }}
  allowedHostFilesystem:
    {{- if .Values.monitoring.enabled }}
    match:
      excludedNamespaces:
        # Prometheus-node-exporter needs access to host to get node metrics
        - jcn1-monitoring
    {{- end }}
    {{- if .Values.fluentbit.enabled }}
    parameters:
      excludedResources:
        # Fluentbit pods need access to host to get log files
        - logging/logging-fluent-bit-.*
    {{- end }}
  {{- end }}

  {{- if .Values.addons.mattermost.enabled }}
  httpsOnly:
    match:
      excludedNamespaces:
        # Mattermost currently does not useIngressTLS hence Ingress is created without TLS field by the operator.
        # Adding exemption, pending https://github.com/mattermost/mattermost-operator/issues/235
        - jcn1-mattermost
  {{- end }}

  namespacesHaveIstio:
    enabled: {{ .Values.istio.enabled }}

  {{- if .Values.logging.enabled }}
  noPrivilegedContainers:
    match:
      excludedNamespaces:
        # Fluentbit needs privileged to read and store the buffer for tailing logs from the nodes
        - jcn1-logging
  {{- end }}

  podsHaveIstio:
    enabled: {{ .Values.istio.enabled }}
    match:
      excludedNamespaces:
        # Istio does not inject sidecars in itself
        - jcn1-istio-operator
        - jcn1-istio-system

  {{- if .Values.monitoring.enabled }}
  restrictedTaint:
    match:
      excludedNamespaces:
        # Prometheus Node Exporter needs to be able to run on all nodes, regardless of taint, to gather node metrics
        - jcn1-monitoring
  {{- end }}

  {{- if .Values.logging.enabled }}
  selinuxPolicy:
    match:
      excludedNamespaces:
        # FluentBit needs selinux option type spc_t
        - jcn1-logging
  {{- end }}

  {{- if or .Values.fluentbit.enabled (or .Values.twistlock.enabled .Values.monitoring.enabled) }}
  volumeTypes:
    match:
      excludedNamespaces:
       {{- if .Values.fluentbit.enabled }}
        # fluent-bit container requires certain host level access to ship logs and for keep track of state
        # https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-kubernetes-filter
        - jcn1-logging
       {{- end }}
       {{- if .Values.twistlock.enabled }}
        # Twistlock requires /dev/log for its syslog daemon.
        # https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/audit/logging.html#
        - jcn1-twistlock
       {{- end }}
       {{- if .Values.monitoring.enabled }}
        # Prometheus node exported requires hostpath hardcoded in upstream chart on which monitoring pkg has a direct dependency
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/daemonset.yaml#L150
        - jcn1-monitoring
       {{- end }}
  {{- end }}
{{- end -}}
