{{- if .Values.twistlock.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: jcn1-twistlock
  labels:
    app.kubernetes.io/name: twistlock
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: enabled
{{- end }}