{{- if .Values.addons.sonarqube.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: jcn1-sonarqube
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: disabled
{{- end }}
