include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: passthrough-vault-fix
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: passthrough-vault-fix 
  DEBUG_ENABLED: "true"

