# testing
include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: describe-resources
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: describe-resources
  DEBUG_ENABLED: "true"
