include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: new-image-packaging
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: new-image-packaging
