{{- $fluxSettingsMattermost := merge .Values.addons.mattermost.flux .Values.flux -}}
{{- if .Values.addons.mattermost.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/component: "collaboration-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  releaseName: mattermost
  targetNamespace: mattermost
  chart:
    spec:
      chart: {{ .Values.addons.mattermost.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: mattermost
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsMattermost | nindent 2 }}

  {{- if .Values.addons.mattermost.postRenderers }}
  postRenderers:
  {{ toYaml .Values.addons.mattermost.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "overlays"
{{- end }}
