{{- if .Values.addons.argocd.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: authservice
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: disabled
  name: jcn1-argocd
{{- end }}
