{{- if .Values.addons.argocd.enabled }}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    {{- if $istioEnabled }}{{- include "istioInjectionLabel" .  | nindent 4 }}{{- end }}
  name: argocd
{{- end }}
