{{- if .Values.neuvector.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: neuvector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: neuvector
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.neuvector.git.repo }}
  ref:
    branch: neuvector-working-branch
    
    
#     {{- include "validRef" .Values.neuvector.git | nindent 4 }}
#   {{ include "gitIgnore" . }}
#   {{- include "gitCreds" . | nindent 2 }}
# {{- end }}
