{{- if .Values.addons.neuvector.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.neuvector "name" "neuvector" "defaults" (include "bigbang.defaults.neuvector" .)) }}
{{- end }}

{{- define "bigbang.defaults.neuvector" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

openshift: {{ .Values.openshift }}

prometheus:
  servicemonitor:
    enabled: {{ .Values.monitoring.enabled }}

imagePullSecrets: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  ingressLabels:
    {{- $gateway := default "public" .Values.neuvector.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.istio) | nindent 4 }}
  nodeCidr: {{ .Values.networkPolicies.nodeCidr }}

istio:
  enabled: {{ .Values.istio.enabled }}
  console:
    gateways:
    - istio-system/{{ default "public" .Values.neuvector.ingress.gateway }}

{{- if .Values.istio.enabled }}
annotations:
  {{ include "istioAnnotation" . }}
{{- end }}

{{- end -}}
