{{- if .Values.prismaCloud.enabled }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: prisma-cloud
  labels:
    app.kubernetes.io/name: prisma-cloud
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}