{{- if .Values.prismaCloud.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.prismaCloud "name" "prisma-cloud" "defaults" (include "bigbang.defaults.prisma-cloud" .)) }}
{{- end }}

{{- define "bigbang.defaults.prisma-cloud" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
domain: {{ default .Values.domain .Values.hostname }}

openshift: {{ .Values.openshift }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
  serviceMonitor:
    enabled: {{ .Values.monitoring.enabled }}
    # conditional passes only for default istio: enabled, mTLS: SCRICT
    {{- if and .Values.istio.enabled (eq (dig "istio" "mtls" "mode" "STRICT" .Values.prismaCloud.values) "STRICT") }}
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
    {{- end }}

imagePullSecrets:
- name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  ingressLabels:
    {{- $gateway := default "public" .Values.prismaCloud.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.istio) | nindent 4 }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  nodeCidr: {{ .Values.networkPolicies.nodeCidr }}

istio:
  enabled: {{ .Values.istio.enabled }}
  console:
    gateways:
    - istio-system/{{ default "public" .Values.prismaCloud.ingress.gateway }}

{{- if .Values.istio.enabled }}
annotations:
  {{ include "istioAnnotation" . }}
{{- end }}

console:
  image:
    imagePullPolicy: {{ .Values.imagePullPolicy }}

sso:
  enabled: {{ .Values.prismaCloud.sso.enabled }}
  client_id: {{ .Values.prismaCloud.sso.client_id }}
  provider_name: {{ .Values.prismaCloud.sso.provider_name }}
  provider_type: {{ .Values.prismaCloud.sso.provider_type }}
  issuer_uri: {{ tpl .Values.prismaCloud.sso.issuer_uri . }}
  idp_url: {{ tpl .Values.prismaCloud.sso.idp_url . }}
  console_url: {{ tpl .Values.prismaCloud.sso.console_url . }}
  groups: {{ .Values.prismaCloud.sso.groups }}
  cert: {{ .Values.prismaCloud.sso.cert | quote }}

{{- end -}}
