{{- if .Values.addons.keycloak.enabled }}
{{ $name := "keycloak" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    istio-injection: disabled-because-keycloak-hates-istio
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: "security-tools"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}