{{- if and .Values.istio.enabled ( or .Values.addons.authservice.enabled .Values.monitoring.sso.enabled .Values.jaeger.sso.enabled ) }}
apiVersion: v1
kind: Namespace
metadata:
  name: jcn1-authservice
  labels:
    {{- if .Values.istio.enabled }}
    istio-injection: enabled
    {{- end }}
    app.kubernetes.io/name: authservice
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}

