{{- if .Values.addons.velero.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.velero "name" "velero" "defaults" (include "bigbang.defaults.velero" .)) }}
{{- end }}

{{- define "bigbang.defaults.velero" -}}

istio:
  enabled: {{ .Values.istio.enabled }}

{{- if .Values.istio.enabled }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

{{- if .Values.monitoring.enabled }}
metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s
  service:
    annotations: {}
    labels: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    {{- if and .Values.istio.enabled (eq (dig "istio" "mtls" "mode" "STRICT" .Values.addons.velero.values) "STRICT") }}
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target
    {{- end }}
  prometheusRule:
    enabled: true
{{- end }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

imagePullSecrets:
- name: private-registry

image:
  pullPolicy: {{ .Values.imagePullPolicy }}

{{- if eq (len .Values.addons.velero.plugins) 0 }}{{- fail "At least one plugin in '.Values.addons.velero.plugins' required. Supported values: aws, azure, csi" }}{{- end }}
initContainers:
{{- range $index, $plugin := .Values.addons.velero.plugins }}
{{- if eq $plugin "aws" }}
  {{$imageName := "registry1.dso.mil/ironbank/opensource/velero/velero-plugin-for-aws"}}
  {{$imageTag := "v1.5.2"}}
  {{- if ge (len $.Values.addons.velero.pluginsImageOverride) (add $index 1) }}
    {{ $imageName = index $.Values.addons.velero.pluginsImageOverride $index }}
  {{- end}}
  {{- if ge (len $.Values.addons.velero.pluginsTagOverride) (add $index 1) }}
    {{ $imageTag = index $.Values.addons.velero.pluginsTagOverride $index }}
  {{- end}}
  - name: velero-plugin-for-aws
    image: {{$imageName}}:{{$imageTag}}
    imagePullPolicy: {{ dig "image" "pullPolicy" "IfNotPresent" $.Values.addons.velero.values }}
    volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 100m
    securityContext:
      capabilities:
        drop: 
          - ALL
{{- end }}
{{- if eq . "azure" }}
  {{$imageName := "registry1.dso.mil/ironbank/opensource/velero/velero-plugin-for-microsoft-azure"}}
  {{$imageTag := "v1.5.2"}}
  {{- if ge (len $.Values.addons.velero.pluginsImageOverride) (add $index 1) }}
    {{ $imageName = index $.Values.addons.velero.pluginsImageOverride $index }}
  {{- end}}
  {{- if ge (len $.Values.addons.velero.pluginsTagOverride) (add $index 1) }}
    {{ $imageTag = index $.Values.addons.velero.pluginsTagOverride $index }}
  {{- end}}
  - name: velero-plugin-for-azure
    image: {{$imageName}}:{{$imageTag}}
    imagePullPolicy: {{ dig "image" "pullPolicy" "IfNotPresent" $.Values.addons.velero.values }}
    volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 100m
    securityContext:
      capabilities:
        drop: 
          - ALL
{{- end }}
{{- if eq . "csi" }}
  {{$imageName := "registry1.dso.mil/ironbank/opensource/velero/velero-plugin-for-csi"}}
  {{$imageTag := "v0.3.2"}}
  {{- if ge (len $.Values.addons.velero.pluginsImageOverride) (add $index 1) }}
    {{ $imageName = index $.Values.addons.velero.pluginsImageOverride $index }}
  {{- end}}
  {{- if ge (len $.Values.addons.velero.pluginsTagOverride) (add $index 1) }}
    {{ $imageTag = index $.Values.addons.velero.pluginsTagOverride $index }}
  {{- end}}
  - name: velero-plugin-for-csi
    image: {{$imageName}}:{{$imageTag}}
    imagePullPolicy: {{ dig "image" "pullPolicy" "IfNotPresent" $.Values.addons.velero.values }}
    volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 100m
    securityContext:
      capabilities:
        drop: 
          - ALL
configuration:
  features: EnableCSI
{{- end }}
{{- end }}

{{- end -}}
