{{- if or .Values.addons.gitlab.enabled .Values.addons.gitlabRunner.enabled }}
{{- if .Values.addons.gitlab.database.host }}
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-database
    namespace: jcn1-gitlab
type: kubernetes.io/opaque
stringData:
    PGPASSWORD: {{ .Values.addons.gitlab.database.password }}
{{- end }}
{{- end }}