istio:
  gateways:
    public:
      tls:
        key: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
        cert: |
          -----BEGIN CERTIFICATE-----
          -----END CERTIFICATE-----