{{- $nexusOldValues := default dict .Values.addons.nexus -}}
{{- $nexusValues := merge $nexusOldValues .Values.addons.nexusRepositoryManager -}}
{{- if and  $nexusValues.enabled $nexusValues.sso.enabled dig "certificateAuthority" "cert" .Values.sso.certificate_authority .Values.sso }}
apiVersion: v1
kind: Secret
metadata:
  name: {{dig "certificateAuthority" "secretName" .Values.sso.secretName .Values.sso}}
  namespace: nexus-repository-manager
type: Opaque
data:
  ca.pem: {{ dig "certificateAuthority" "cert" .Values.sso.certificate_authority .Values.sso | b64enc }}
{{- end }}
