{{- if .Values.addons.anchore.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: anchore
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: enabled
  name: anchore
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-helm-test-egress
  namespace: anchore
spec:
  podSelector:
    matchLabels:
      helm-test: enabled
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
{{- end }}
