{{- if .Values.jaeger.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.jaeger "name" "jaeger" "defaults" (include "bigbang.defaults.jaeger" .)) }}
{{- end }}

{{- define "bigbang.defaults.jaeger" -}}
imagePullSecrets:
  - name: private-registry
hostname: {{ .Values.hostname }}
istio:
  enabled: {{ .Values.istio.enabled }}
  jaeger:
    hosts:
    - tracing{{ if .Values.addons.keycloak.enabled }}.admin{{ end }}.{{ .Values.hostname }}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}
elasticsearch:
  enabled: {{ .Values.logging.enabled }}
jaeger:
  spec:
    allInOne:
      labels:
        protect: keycloak
    query:
      labels:
        protect: keycloak
{{- end -}}