{{- if .Values.istio.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.istio "name" "istio" "defaults" (include "bigbang.defaults.istio" .)) }}
{{- end }}

{{- define "bigbang.defaults.istio" -}}
hostname: {{ .Values.hostname }}

tracing:
  enabled:  {{ .Values.jaeger.enabled }}

imagePullSecrets:
  - private-registry

openshift: {{ .Values.openshift }}

{{- if .Values.addons.keycloak.enabled }}
extraServers:
- port:
    name: https-keycloak
    protocol: TLS
    number: 8443
  hosts:
    - keycloak.{{ .Values.hostname }}
  tls:
    mode: PASSTHROUGH

gateway:
  hosts:
    - "*.admin.{{ .Values.hostname }}"
{{- end }}
{{- end -}}
