{{- if .Values.metrics.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.metrics "name" "metrics" "defaults" (include "bigbang.defaults.metrics" .)) }}
{{- end }}

{{- define "bigbang.defaults.metrics" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
domain: {{ $domainName }}

istio:
  enabled: {{ .Values.istio.enabled }}
  injection: {{ ternary "enabled" "disabled" (and .Values.istio.enabled (eq (dig "istio" "injection" "enabled" .Values.metrics) "enabled")) }}

metrics:
  enabled: {{ .Values.monitoring.enabled }}

serviceMonitor:
  enabled: {{ .Values.monitoring.enabled }}
  dashboards:
    namespace: monitoring

# Default to 2 replicas for HA
replicas: 2

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

{{- end }}
