{{- if .Values.spire.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: spire
  labels:
    app.kubernetes.io/name: spire
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: disabled
{{- end }}