{{- if and (not .Values.offline) (and .Values.logging.enabled .Values.promtail.enabled (eq .Values.logging.engine "plg")) }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: promtail
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.promtail.git.repo }}
  ref:
    {{- include "validRef" .Values.promtail.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
