{{- if or .Values.loki.enabled .Values.promtail.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.loki "name" "loki" "defaults" (include "bigbang.defaults.loki" .)) }}
{{- end }}

{{- define "bigbang.defaults.loki" -}}
hostname: {{ .Values.hostname }}

openshift: {{ .Values.openshift }}

istio:
  enabled: {{ .Values.istio.enabled }}

imagePullSecrets:
  - name: private-registry

image:
  pullPolicy: {{ .Values.imagePullPolicy }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

istio:
  enabled: {{ .Values.istio.enabled }} 

global:
  createGlobalConfig: true
  existingSecretForConfig: loki-config

  objectStorage:
    endpoint: {{ .Values.loki.objectStorage.endpoint }}
    region: {{ .Values.loki.objectStorage.region }}
    bucketnames: {{ .Values.loki.objectStorage.bucketNames }}
    access_key_id: {{ .Values.loki.objectStorage.accessKey }}
    secret_access_key: {{ .Values.loki.objectStorage.accessSecret }}

minio:
  enabled: {{ eq .Values.loki.objectStorage.type "minio" }}

{{- if .Values.istio.enabled }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end }}

loki:
  enabled: {{ eq .Values.loki.strategy "monolith" }}
{{- if .Values.loki.enterprise.enabled }}
  image:
    registry: registry.dso.mil
    repository: platform-one/big-bang/apps/sandbox/loki/enterprise-logs
    tag: v1.3.0
    pullPolicy: IfNotPresent
{{- end }}

  serviceMonitor:
    enabled: {{ .Values.monitoring.enabled }}

loki-simple-scalable:
  enabled: {{ eq .Values.loki.strategy "scalable" }}

  imagePullSecrets:
    - name: private-registry
  {{- if .Values.loki.enterprise.enabled }}
  nameOverride: loki

  loki:
    image:
      registry: registry.dso.mil
      repository: platform-one/big-bang/apps/sandbox/loki/enterprise-logs
      tag: v1.3.0
      pullPolicy: IfNotPresent
  {{- end }}
  serviceMonitor:
    enabled: {{ .Values.monitoring.enabled }}

gel:
  enabled: {{ .Values.loki.enterprise.enabled }}

  image:
    pullSecrets:
    - private-registry
  tokengen:
    annotations:
      sidecar.istio.io/inject: "false"
  license:
    contents: {{ .Values.loki.enterprise.licenseContents }}
{{- end -}}
