{{- if and .Values.addons.knativeoperator.enabled ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: knative-operator
  labels:
    app.kubernetes.io/name: knative-operator
    app.kubernetes.io/component: "addons"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}